---
title: "Module 3: Conditional Probability Notes"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Conditional Probability

Let $B$ an event such that $P(B) > 0$, then the probability of event $A$ given $B$ is the probability of both event $A$ and $B$ divided by the probability of $B$.

$$P(A ~|~ B) = \frac{P(A \cap B)}{P(B)}$$


### Example

* Let $B$ be an odd die roll, $B = \{1,3,5\}$, $P(B) = 3/6$
* Let $A$ be a die roll of 1 or 2, $A = \{1,2\}$, $P(A) = 2/6$ 

Given event $B$... (a roll was odd)

$$P(A ~|~ B) = \frac{P(A \cap B)}{P(B)} = \frac{P(\text{die roll of 1})}{P(B)} = \frac{1/6}{3/6} = \frac{1}{3}$$

## Bayes' Rule

Bayes' rule allows us to calculate $P(B ~|~ A)$ when we have $P(A ~|~ B)$ as long as we have  

* Probability of $B$, $P(B)$  

$$P(B ~|~ A) = \frac{P(A ~|~ B)P(B))}{P(A ~|~ B)P(B) + P(A ~|~ B^c)P(B^c)}$$

### Diagnostic Test for a Disease 

Given we have a diagnostic test that attempts to detect a disease within a subject, let:  

* $+$ be the event that the result of a diagnostic test is positive  
* $-$ be the event that the result of a diagnostic test is negative  
* $D$ be the event that the subject of the test actually has the disease  
* $D^c$ be the event that the subject of the test is free of the disease  

### Performance measures 

* **Sensitivity** of the test is the probability that the test is *positive* given the subject *has* the disease $P(+ ~|~ D)$  
* **Specificity** of the test is the probability that the test is *negative* given the subject *does not* have the disease $P(- ~|~ D^c)$  

### Predictive values

* **Positive Predictive Value** is the probability the subject *has* the disease given a *positive* test, $P(D ~|~ +)$  
* **Negative Predictive Value** is the probability the subject *does not* have the disease given a *negative* test, $P(D^c ~|~ -)$  
* **Prevalence of the disease** is the marginal probability of disease $P(D)$

### Example

A study comparing the efficacy of HIV tests, reports on an experiment which concluded that HIV antibody tests have a sensitivity of 99.7% 
and a specificity of 98.5% Suppose that a subject, from a population with a .1% prevalence of HIV, receives a positive test result. 
What is the positive predictive value?

So far, we know:  

* **Sensitivity:** $P(+ ~|~ D) = 0.997$  
* **Specificity:** $P(- ~|~ D^c) = 0.985$
* **Prevelance:** $P(D) = 0.001$

Calculating **Positive Predictive Value** $P(D ~|~ +)$ using Bayes' rule:

$$P(D ~|~ +)  = \frac{P(+ ~|~ D)P(D)}{P(+ ~|~ D)P(D) + P(+ ~|~ D^c)P(D^c)}$$

We have most of these, except:

* $P(+ ~|~ D^c)$, the probability the subject tests positive when disease free, is the complement of specificity, $1 - P(- ~|~ D^c)$
* $P(D^C)$, the probabity of not having the disease, is the compliment of the probability of having it, $1 - P(D)$

$$P(D ~|~ +)  = \frac{P(+ ~|~ D)P(D)}{P(+ ~|~ D)P(D) + (1 - P(- ~|~ D^c))(1 - P(D))} \\ = \frac{0.997 \times 0.001}{(0.997 \times 0.001) + (1 - 0.985) \times (1 - 0.001)} \\ = 0.062 $$

## Diagnostic Likelihood Ratios

Diagnostic likelihood ratios are used after a positive or negative test to determine the new, post-test odds of disease.

* **Diagnostic Likelihood Ratio of a positive test**, $DLR_+$ is the probability of a positive test given having the disease divided by the probability of positive test given NOT having the disease.

$$DLR_+ = \frac {P(+ ~|~ D)}{P(+ ~|~ D^c)} = \frac{\text{sensitivity}}{1-specificity}$$

* **Diagnostic Likelihood Ratio of a negative test**, $DLR_-$ is the probability of a negative test given having the disease divided by the probability of negative test given NOT having the disease.

$$DLR_- = \frac {P(- ~|~ D)}{P(- ~|~ D^c)} = \frac{\text{1 - sensitivity}}{specificity}$$

For a positive test, $DLR_+$ is the factor by which we would multiply the pre-test odds to get the new post-test odds.

Ok, let's toss Bayes' Rule in there now because, you know... math.

$$DLR_+ = \frac {P(+ ~|~ D)}{P(+ ~|~ D^c)} = 
\dfrac{
  \dfrac{
    P(+ ~|~ D)P(D)
  }{
    P(+ ~|~ D)P(D) + P(+ ~|~ D^c)P(D^c)
  }
}{
  \dfrac{
    P(+ ~|~ D^c)P(D^c)
  }{
    P(+ ~|~ D^c)P(D^c) + P(+ ~|~ D)P(D)
  }
}
= \dfrac{
    P(+ ~|~ D)
}{
    P(+ ~|~ D^c)
} \times 
\dfrac {
  P(D)
}{
  P(D^c)
}$$

$$DLR_- = \frac {P(- ~|~ D)}{P(- ~|~ D^c)} = 
\dfrac{
  \dfrac{
    P(- ~|~ D)P(D)
  }{
    P(- ~|~ D)P(D) + P(- ~|~ D^c)P(D^c)
  }
}{
  \dfrac{
    P(- ~|~ D^c)P(D^c)
  }{
    P(- ~|~ D^c)P(D^c) + P(- ~|~ D)P(D)
  }
}
= \dfrac{
    P(- ~|~ D)
}{
    P(- ~|~ D^c)
} \times 
\dfrac {
  P(D)
}{
  P(D^c)
}$$


## Independence
Event $A$ is independent of event $B$ (assuming $P(B) > 0$) if:

 * $P(A ~|~ B) = P(A)$ 

Equivantly:

 * $P(A \cap B) = P(A) \times P(B)$
 
 If event $A$ is independent of $B$ then we would also know that compliments are independent.
 
  * $A$ is independent of $B^C$  
  * $A^C$ is independent of $B$  
  * $A^C$ is independent of $B^C$
  
### Independent and Identically Distributed (IID) Random Variables

Random variables are considered IID if they are independent and identically distributed.

* **Independent:** statistically unrelated from one another  
* **Identically Distributed:**  all having been drawn from the same population distribution  

## Exercises

### Question 1
I pull a card from a deck and do not show you the result. I say that the resulting card is a heart. What is the probability that it is the queen of hearts?

**ANSWER**  
Let $H$ be the event the card is from the heart suit  
Let $Q$ be the event the card is a queen  

$$P(H) = \dfrac {13}{52}$$

$$P(Q) = \dfrac {4}{52}$$

$$P(Q ~|~ H) 
= \dfrac{P(Q \cap H)}{P(H)} 
= \dfrac {1/52}{13/52} 
= \dfrac {1}{13} 
= \color{blue}{`r 1/13`}$$ 

### Question 2
The odds associated with a probability, $p$, are defined as?

**ANSWER**  
The odds are the ratio of the probability of an event to the probability of it not occurring (its compliment).

$$\color{blue}{odds = \dfrac {p}{(1-p)}}$$

### Question 3
The probability of getting two sixes when rolling a pair of dice is?

**ANSWER**  
Let $A$ be the event of getting a 6 on the first die roll  
Let $B$ be the event of getting a 6 on the second die roll  

$$P(A) = \dfrac {1}{6}$$
$$P(B) = \dfrac {1}{6}$$

Given that the two die rolls are independent

$$P(A \cap B) = P(A) \times P(B) 
= \dfrac {1}{6} \times \dfrac {1}{6} 
= \dfrac {1}{36} 
= \color{blue}{`r 1/36`}$$

### Question 4
The probability that a manuscript gets accepted to a journal is 12% (say). However, given that a revision is asked for, the probability that it gets accepted is 90%. Is it possible that the probability that a manuscript has a revision asked for is 20%? 

**ANSWER**  
Let $A$ be the event that a manuscript gets accepted  
Let $R$ be the event that a revision is requested

$$P(A) = 0.12$$
$$P(A ~|~ R) = 0.90$$

Using these we substitute into the conditional probability...

$$P(A ~|~ R) = \frac{P(A \cap R)}{P(R)}$$
$$0.90 = \frac{P(A \cap R)}{0.20}$$

$$P(A \cap R) = 0.90 \times 0.20 = \color{blue}{`r 0.9 * 0.2`}$$

<span style="color:blue">The answer is no, it is not possible since the probability of both $A$ and $R$, $P(A \cap R)$, cannot be greater than the probability of event $A$ alone occurring.</span>

### Question 5
Suppose 5% of housing projects have issues with asbestos. The sensitivity of a test for asbestos is 93% and the specificity is 88%. What is the probability that a housing project has no asbestos given a negative test expressed as a percentage to the nearest percentage point? 

**ANSWER**  
Let:  

* $A$ be the event a housing project has an asbestos issue  
* $+$ be the event that the result of the asbestos test is positive   
* $-$ be the event that the result of the asbestos test is negative  

Provided values

* **Sensitivity:** $P(+ ~|~ A) = 0.93$  
* **Specificity:** $P(- ~|~ A^c) = 0.88$
* **Prevelance:** $P(A) = 0.05$

Calculated values that will help us answer the question

* $P(A^C) = 1 - P(A) = 0.95$  
* $P(- ~|~ A) = 1 - P(+ ~|~ A) = `r 1 - 0.93`$  

We are being asked to calculate the **negative predictive value** $P(A^c ~|~ -)$.  Don't worry, your good buddy Bayes is here to help.

$$P(A^c ~|~ -)  =
\dfrac{
  P(- ~|~ A^c)P(A^c)
}{
  P(- ~|~ A^c)P(A^c) + P(- ~|~ A)P(A)
} \\  = 
\dfrac{
  0.88 \times 0.95
}{
  0.88 \times 0.95 + 0.07 \times 0.05
} \\ =
\color{blue}{`r (0.88 * 0.95) / ((0.88 * 0.95) + (0.07 * 0.05))`}
$$

<span style="color:blue">The probability that a housing project has no asbestos given a negative test expressed as a percentage to the nearest percentage point is **100%** </span>




























































