---
title: "Module 4: Expected Values Notes"
output: 
  html_document:
    fig_width: 10
    fig_height: 8
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(UsingR)
library(ggplot2)
library(reshape2)
```

## Expected Value

The expected value of a random variable $X$, $E(X)$, is a measure of its central tendency.

This is the center of a density or mass function (so it applies to both discrete and continuous random variables).

For discrete random variable $X$ with $PMF = p(x)$, it is defined as the sum of of all possible values of $x$ times the probability $p(x)$

$$E[X] = \sum\limits_x (x \times p(x))$$
For a coin flip, 0 = tails, 1 = heads:

$$E[X] = \sum\limits_x (x \times p(x)) = (0 \times \dfrac{1}{2}) + (1 \times \dfrac{1}{2}) = \dfrac{1}{2} = 0.5$$
For six sided die:

$$E[X] = \sum\limits_x (x \times p(x)) = (1 \times \dfrac{1}{6}) + (2 \times \dfrac{1}{6}) + (3 \times \dfrac{1}{6}) + 
                                         (4 \times \dfrac{1}{6}) + (5 \times \dfrac{1}{6}) + (6 \times \dfrac{1}{6}) = \dfrac {21}{6} = 3.5$$


## Summary

 * **Expected Values** are properties of distributions    
 * **Population Mean** is the center of mass of a population  
 * **Sample Mean**   
    * is the center of mass of the observed data  
    * is an estimate of the **Population Mean**  
    * is unbiased: the **Population Mean** of its distribution is the mean that it’s trying to estimate  
 * The more data that goes into a **Sample Mean**, the more concentrated its density/mass function is around the **Population Mean**
 
 
## Exercises
 
1. A standard die takes the values 1, 2, 3, 4, 5, 6 with equal probability. What is the expected value?

$$E[X] = \sum\limits_x (x \times p(x)) = (1 \times \dfrac{1}{6}) + (2 \times \dfrac{1}{6}) + (3 \times \dfrac{1}{6}) + 
                                         (4 \times \dfrac{1}{6}) + (5 \times \dfrac{1}{6}) + (6 \times \dfrac{1}{6}) = \dfrac {21}{6} = 3.5$$

2. Consider a density that is uniform from -1 to 1. (I.e. has height equal to 1/2 and looks like a box starting at -1 and ending at 1). What is the mean of this distribution?



3. If a population has mean $μ$ , what is the mean of the distribution of averages of 20 observations from this distribution?


4. You are playing a game with a friend where you flip a coin and if it comes up heads you give her $X$ dollars and if it comes up tails she gives you YY dollars. The odds that the coin is heads is dd. What is your expected earnings? 


5. If you roll ten standard dice, take their average, then repeat this process over and over and construct a histogram what would it be centered at? 

