---
title: "cheatsheet"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


$$P(A ~|~ B) = \frac{P(A \cap B)}{P(B)}$$
Solving for $P(A \cap B)$...

$$P(A \cap B) = P(A ~|~ B) \times P(B)$$

$$P(B ~|~ A) = \dfrac{P(B \cap A)}{P(A)} = P(A ~|~ B) \times \dfrac{P(B)}{P(A)}$$

## Set Operators
Let $A$ be the set $\{1, 3\}$

Let $B$ be the set $\{1, 3, 5\}$  

| Expression                    | Description                                                                 |
| ----------------------------- | --------------------------------------------------------------------------- |
| $A \ni 3$                     | $A$ *"owns"* or *"has element"* $3$                                         |
| $3 \in A$                     | $3$ *"belongs to"* or *"is an element of"* $A$                              |
| $5 \notin A$                  | $5$ *"does not belong to"* or *"is not an element of"* $A$                  |
| $A \subset B$                 | Set $A$ is a proper subset of set $B$  (not equal)                          |
| $B \supset A$                 | Set $B$ is a proper superset of set $A$ (not equal)                         |
| $A \cup B = \{1, 3, 5\}$      | Union of sets $A$ and $B$                                                   |
| $A \cap B = \{1, 3\}$         | Intersection of sets $A$ and $B$                                            |


## Probability
| Expression                    | Description                                                                 |
| ----------------------------- | --------------------------------------------------------------------------- |
| $P(A \cup B)$                 | The probabiity of at least one of event $A$ or $B$ occuring (union)         |
| $P(A \cap B)$                               | The probabiity of both event $A$ and $B$ occuring (intersection)            |
| $P(A$ &#124; $B) = \frac{P(A \cap B)}{P(B)}$ | Conditional probability, the probability of event $A$ given event $B$ has occurred                    |
| $P(A \cup B) = P(A) + P(B) - P(A \cap B)$    | For any two events the probability at least one occurs is the sum of their probabilities minus their intersection |

### Bayes' Rule
$$P(B ~|~ A) = \frac{P(A ~|~ B)P(B))}{P(A ~|~ B)P(B) + P(A ~|~ B^c)P(B^c)}$$                  




